// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAtYEw2vjRYRO-cwHmSVeJ985vJIhfzcR4',
    appId: '1:408402580233:web:f7b770492bdb1174b079d8',
    messagingSenderId: '408402580233',
    projectId: 'notes-4cf78',
    authDomain: 'notes-4cf78.firebaseapp.com',
    storageBucket: 'notes-4cf78.appspot.com',
    measurementId: 'G-D1QYFFWRD9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCxIep5ouX_13PCTTgm0BWGNqHFQOK4x6Q',
    appId: '1:408402580233:android:7620518699748cd0b079d8',
    messagingSenderId: '408402580233',
    projectId: 'notes-4cf78',
    storageBucket: 'notes-4cf78.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCA82o39fztYQCAtEZBMlKBFRmqStj0KAA',
    appId: '1:408402580233:ios:543d5696f7077548b079d8',
    messagingSenderId: '408402580233',
    projectId: 'notes-4cf78',
    storageBucket: 'notes-4cf78.appspot.com',
    iosClientId: '408402580233-p0uehf9nh0ha215rvcfevkhdrq5hdp27.apps.googleusercontent.com',
    iosBundleId: 'ak.fproject.notes',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCA82o39fztYQCAtEZBMlKBFRmqStj0KAA',
    appId: '1:408402580233:ios:da4f995fda5bd83cb079d8',
    messagingSenderId: '408402580233',
    projectId: 'notes-4cf78',
    storageBucket: 'notes-4cf78.appspot.com',
    iosClientId: '408402580233-uh9leb9jn9edjk3kca108h5cvuduipk9.apps.googleusercontent.com',
    iosBundleId: 'ak.fproject.notes.RunnerTests',
  );
}
